PROJECT TITLE:
An Analysis of Police Officer Stop Data

TEAM MEMBERS:
J.D. Strode
Vaidehee Shah
Octavio Origel
Peter Sparks
Melissa Mongrella

PROJECT DESCRIPTION/OUTLINE:
Our project is analyzing the The Stanford Open Project's Chicago dataset. 
We have chosen four questions from the dataset to further understand the nuances of traffic stops in the city.

RESEARCH QUESTIONS TO ANSWER:

1) How does the race and gender of the police officer affect the race and gender of the person getting stopped?
2) What area of Chicago do the most stops occur?
3) What are the most common time points for a stop to occur?
4) Was a citation issued?
5) What are the general demographics of people who get pulled over?

DATASETS TO BE USED:
We will be using the Stanford Opening Policing Project (https://openpolicing.stanford.edu/)

ROUGH BREAKDOWN OF TASKS:
J.D. Strode - Will look at demographic relationships (Question 1)
Vaidehee Shah - Will look at the most common time points for a stop to occur (Question 3)
Octavio Origel - Will examine if age influences the occurrence of citations or arrests 
Peter Sparks - Will look at location data
Melissa Mongrella - Will look at the general demographics of people who get pulled over

In [4]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
import json

# Import API key
# from api_key import g_key

# Incorporated citipy to determine city based on latitude and longitude
# from citipy import citipy

In [5]:
# File to Load (Remember to Change These)
crime_data = "crime_data/chicagodata.csv"

# Read Purchasing File and store into Pandas data frame
df = pd.read_csv(crime_data, encoding="utf-8")

C:\Users\jdstr\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (9,16,17,19,20) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [6]:
df.head()

,raw_row_number,date,time,location,lat,lng,subject_age,subject_race,subject_sex,officer_id_hash,...,officer_race,officer_sex,officer_years_of_service,type,violation,arrest_made,citation_issued,outcome,raw_race,raw_driver_race
0,1,2012-01-06,09:00:00,700 LINCOLN W,NaN,NaN,23.0,black,male,a6d791f976,...,white,male,17.0,vehicular,DRIVING ON SUSPENDED LICENSE,True,NaN,arrest,BLACK,NaN
1,2,2012-01-01,00:00:00,NaN,NaN,NaN,23.0,hispanic,male,81da9fab7e,...,white,male,2.0,vehicular,DRIVING/NEVER ISSUED LICENSE,True,NaN,arrest,HISPANIC,NaN
2,3,2012-01-01,01:00:00,0 NORTHWEST HWY & HILLSIDE RD S,NaN,NaN,38.0,white,female,NaN,...,NaN,NaN,NaN,vehicular,DRIVING ON SUSPENDED LICENSE,True,NaN,arrest,WHITE,NaN
3,4,2012-01-01,01:00:00,108 LAMON AVE N,NaN,NaN,35.0,black,male,048359e7c8,...,black,male,8.0,vehicular,IVC - FAIL TO STOP/SIGNAL CROSSWALK,True,NaN,arrest,BLACK,NaN
4,5,2012-01-01,01:00:00,3451 177TH ST W,NaN,NaN,20.0,black,male,NaN,...,NaN,NaN,NaN,vehicular,IVC - DRIVING 15-20 MPH ABOVE SPEED LIMIT,True,NaN,arrest,BLACK,NaN